import { createRequire } from "node:module";
import { afterEach, describe, expect, it } from "vitest";
import {
  area as areaTs,
  centroid as centroidTs,
  offsetPolygon as offsetPolygonTs,
  perimeter as perimeterTs,
  pointInPolygon as pointInPolygonTs,
  type Point,
  type Polygon,
} from "@thoth/domain";
import {
  __resetGeometryWasmForTests,
  centroidPreferWasm,
  isGeometryWasmReady,
  wasmArea,
} from "./geometryWasm";

/**
 * Proves the compiled `thoth-bindings` WASM module and the TS
 * `packages/domain/src/spatial/geometry.ts` it mirrors agree, for the one
 * call site this migration pass cut over (`PlatDrawing.tsx`'s centroid) and
 * the rest of the ported slice.
 *
 * This loads the `--target nodejs` artifact
 * (`apps/web/src/wasm/thoth-bindings-node-test/`), generated by
 * `yarn build:wasm` from the exact same `crates/thoth-bindings` source as
 * the `--target web` artifact `geometryWasm.ts` uses in the browser (see
 * `scripts/build-wasm.sh` for why two targets exist). Node's `fetch` can't
 * load `file://` URLs, so the browser-oriented `web` target can't be
 * exercised directly under Vitest/Node — `createRequire` sidesteps that by
 * loading the CommonJS `nodejs` target the normal Node module system, not a
 * bundler-mediated import.
 *
 * If this test ever fails after a `thoth-spatial` or `thoth-bindings`
 * change, regenerate the wasm artifacts first (`yarn build:wasm`) — a stale
 * committed artifact is the most likely cause, not a real regression.
 */
const require = createRequire(import.meta.url);
const wasmGeometry = require("../wasm/thoth-bindings-node-test/thoth_bindings.cjs") as {
  area(polygon: Polygon): number;
  perimeter(polygon: Polygon): number;
  centroid(polygon: Polygon): Point;
  pointInPolygon(point: Point, polygon: Polygon): boolean;
  offsetPolygon(polygon: Polygon, distance: number): Polygon | null;
};

const square: Polygon = [
  { x: 0, y: 0 },
  { x: 10, y: 0 },
  { x: 10, y: 10 },
  { x: 0, y: 10 },
];

const triangle: Polygon = [
  { x: 0, y: 0 },
  { x: 8, y: 0 },
  { x: 4, y: 6 },
];

// A concave "L" shape — exercises the centroid's area-weighting beyond a
// trivially symmetric polygon.
const lShape: Polygon = [
  { x: 0, y: 0 },
  { x: 6, y: 0 },
  { x: 6, y: 3 },
  { x: 3, y: 3 },
  { x: 3, y: 6 },
  { x: 0, y: 6 },
];

const polygons = { square, triangle, lShape };

describe("thoth-bindings WASM geometry matches the TS implementation", () => {
  for (const [name, polygon] of Object.entries(polygons)) {
    it(`area(${name})`, () => {
      expect(wasmGeometry.area(polygon)).toBeCloseTo(areaTs(polygon), 9);
    });

    it(`perimeter(${name})`, () => {
      expect(wasmGeometry.perimeter(polygon)).toBeCloseTo(perimeterTs(polygon), 9);
    });

    it(`centroid(${name})`, () => {
      const wasmC = wasmGeometry.centroid(polygon);
      const tsC = centroidTs(polygon);
      expect(wasmC.x).toBeCloseTo(tsC.x, 9);
      expect(wasmC.y).toBeCloseTo(tsC.y, 9);
    });
  }

  it("pointInPolygon agrees for interior, exterior, and edge points", () => {
    const cases: Point[] = [
      { x: 5, y: 5 }, // interior
      { x: 50, y: 50 }, // exterior
      { x: 0, y: 5 }, // on an edge
    ];
    for (const point of cases) {
      expect(wasmGeometry.pointInPolygon(point, square)).toBe(pointInPolygonTs(point, square));
    }
  });

  it("offsetPolygon agrees for a valid inset", () => {
    const wasmResult = wasmGeometry.offsetPolygon(square, 1);
    const tsResult = offsetPolygonTs(square, 1);
    expect(wasmResult).not.toBeNull();
    expect(tsResult).not.toBeNull();
    expect(wasmResult).toHaveLength(tsResult!.length);
    wasmResult!.forEach((p, i) => {
      expect(p.x).toBeCloseTo(tsResult![i].x, 9);
      expect(p.y).toBeCloseTo(tsResult![i].y, 9);
    });
  });

  it("offsetPolygon agrees that an oversized offset collapses to null, not an error", () => {
    expect(wasmGeometry.offsetPolygon(square, 100)).toBeNull();
    expect(offsetPolygonTs(square, 100)).toBeNull();
  });
});

describe("geometryWasm.ts wrapper (production, --target web module)", () => {
  afterEach(() => {
    __resetGeometryWasmForTests();
  });

  it("is not ready until initGeometryWasm() resolves", () => {
    expect(isGeometryWasmReady()).toBe(false);
  });

  it("throws a clear, catchable Error (not an obscure TypeError) when called before init", () => {
    expect(() => wasmArea(square)).toThrowError(/called before initGeometryWasm\(\) resolved/);
  });

  it("centroidPreferWasm falls back to the TS implementation before wasm is ready", () => {
    // No initGeometryWasm() call in this test — this exercises exactly the
    // "wasm hasn't loaded yet" path every real page load starts in.
    const result = centroidPreferWasm(square);
    const tsResult = centroidTs(square);
    expect(result).toEqual(tsResult);
  });
});
