/**
 * Typed wrapper around the `thoth-bindings` wasm-bindgen module — the one
 * geometry vertical slice ported to Rust so far (`area`, `perimeter`,
 * `centroid`, `pointInPolygon`, `offsetPolygon`, all mirroring
 * `packages/domain/src/spatial/geometry.ts` exactly; see
 * `crates/thoth-bindings/src/geometry.rs`).
 *
 * ## Why this file exists (not just importing the generated module directly)
 * `apps/web/src/wasm/thoth-bindings/thoth_bindings.d.ts` is generated by
 * `wasm-bindgen` (`yarn build:wasm` → `scripts/build-wasm.sh`) and types
 * every `JsValue` parameter/return as `any` — there is no way for
 * wasm-bindgen to know the JS shape crossing an opaque `JsValue` boundary.
 * This module re-types those functions against `@thoth/domain`'s own
 * `Point`/`Polygon`, so callers get the same type safety as calling the TS
 * implementation directly.
 *
 * ## Wire format (must match `crates/thoth-bindings/src/geometry.rs`)
 * Plain JS objects/arrays — `Point` as `{x, y}`, `Polygon` as `Point[]` — and
 * `null` (never `undefined`) for `offsetPolygon`'s optional result. No
 * `JSON.stringify`/`parse` needed on this side either.
 *
 * ## Lifecycle — read before using
 * The wasm module is fetched and instantiated asynchronously. Call
 * `initGeometryWasm()` once, e.g. at app bootstrap in `main.tsx` — it is
 * idempotent and safe to call again (subsequent calls return the same
 * promise). Every `wasm*` function below throws a clear, actionable `Error`
 * if called before that promise resolves, rather than an obscure
 * "cannot read properties of undefined" — check `isGeometryWasmReady()`
 * first, or prefer `centroidPreferWasm()` (below) at call sites that must
 * never block on wasm loading.
 *
 * ## Error handling across the boundary
 * A Rust `Result::Err(JsValue)` crosses as a **thrown plain string** (the
 * message set in `crates/thoth-bindings/src/geometry.rs`), not a thrown
 * `Error` instance. Every function below normalizes that into a real
 * `Error` so `instanceof Error` / `.stack` work as callers expect. A Rust
 * *panic* (a bug, not a validation failure) would instead surface as a
 * console-logged stack trace via `console_error_panic_hook` (installed by
 * `initGeometryWasm()`) and the wasm instance would need reloading — none of
 * the functions in this slice are expected to panic in normal use.
 *
 * ## Ownership
 * Nothing here hands back a pointer or anything needing an explicit
 * `.free()` — every value is a freshly-allocated, plain JS value.
 */
import wasmInit, {
  area as wasmAreaRaw,
  centroid as wasmCentroidRaw,
  offsetPolygon as wasmOffsetPolygonRaw,
  perimeter as wasmPerimeterRaw,
  pointInPolygon as wasmPointInPolygonRaw,
  setPanicHook,
} from "@/wasm/thoth-bindings/thoth_bindings.js";
import { centroid as centroidTs, type Point, type Polygon } from "@thoth/domain";

let initPromise: Promise<void> | null = null;
let ready = false;

/**
 * Fetch + instantiate the wasm module and install the panic hook. Idempotent:
 * the first call kicks off loading; every call after that (including ones
 * made while loading is still in flight) returns the same promise.
 */
export function initGeometryWasm(): Promise<void> {
  if (!initPromise) {
    initPromise = wasmInit().then(() => {
      setPanicHook();
      ready = true;
    });
  }
  return initPromise;
}

/** `true` once the promise returned by {@link initGeometryWasm} has resolved. */
export function isGeometryWasmReady(): boolean {
  return ready;
}

/**
 * Reset internal ready/init state. Test-only: lets a test simulate "wasm not
 * loaded yet" without needing a second real module instance. Not exported
 * from any public entry point apps/web itself imports from.
 */
export function __resetGeometryWasmForTests(): void {
  initPromise = null;
  ready = false;
}

function call<T>(fn: () => T, what: string): T {
  if (!ready) {
    throw new Error(
      `thoth-bindings wasm: ${what}() called before initGeometryWasm() resolved. ` +
        "Call `await initGeometryWasm()` once (e.g. at app startup) before using this module.",
    );
  }
  try {
    return fn();
  } catch (e) {
    if (e instanceof Error) {
      throw e;
    }
    // Result::Err(JsValue) crosses as a thrown plain string, not an Error.
    throw new Error(`thoth-bindings wasm: ${what} failed: ${String(e)}`);
  }
}

/** Absolute area of a polygon in plan units². See `area()` in `packages/domain/src/spatial/geometry.ts`. */
export function wasmArea(polygon: Polygon): number {
  return call(() => wasmAreaRaw(polygon) as number, "area");
}

/** Perimeter of a closed polygon in plan units. */
export function wasmPerimeter(polygon: Polygon): number {
  return call(() => wasmPerimeterRaw(polygon) as number, "perimeter");
}

/** Area-weighted centroid of a polygon (vertex mean if degenerate). */
export function wasmCentroid(polygon: Polygon): Point {
  return call(() => wasmCentroidRaw(polygon) as Point, "centroid");
}

/** Ray-casting point-in-polygon test; edge points count as inside. */
export function wasmPointInPolygon(point: Point, polygon: Polygon): boolean {
  return call(() => wasmPointInPolygonRaw(point, polygon) as boolean, "pointInPolygon");
}

/** Inset/outset a polygon by `distance`; `null` (not a thrown error) if the offset collapses the ring. */
export function wasmOffsetPolygon(polygon: Polygon, distance: number): Polygon | null {
  return call(() => wasmOffsetPolygonRaw(polygon, distance) as Polygon | null, "offsetPolygon");
}

/**
 * Centroid of a polygon, preferring the WASM geometry core once it has
 * finished loading, and transparently falling back to the TS implementation
 * otherwise (before `initGeometryWasm()` resolves, or if a wasm call ever
 * throws). This is the one call site this migration pass actually cut over
 * (see `apps/web/src/features/survey/PlatDrawing.tsx`) — the fallback makes
 * the swap reversible and safe: worst case, behavior is identical to before
 * this change.
 */
export function centroidPreferWasm(polygon: Polygon): Point {
  if (ready) {
    try {
      return wasmCentroid(polygon);
    } catch {
      // Never let a wasm hiccup break rendering — fall through to TS.
    }
  }
  return centroidTs(polygon);
}
